config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  resources :generes
  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
    # root to: 'devise/sessions#new'
  end
  devise_for :users
  get 'users_list', to: 'users#index', as: 'users_list'
  get 'dashboard', to: 'home#index', as: 'home_dashboard'
  get '/home/turbo_frame_form' => 'home#turbo_frame_form', as: 'turbo_frame_form'
  post '/home/turbo_frame_submit' => 'home#turbo_frame_submit', as: 'turbo_frame_submit'
  patch '/drag/item'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/genere.rb
class Genere < ApplicationRecord
  has_many :uploads
  acts_as_list
end

app/models/upload.rb
class Upload < ApplicationRecord
  belongs_to :genere
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  enum role: { basic: 0, admin: 1 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_secure_password
  has_many :uploads, dependent: :destroy

  after_commit lambda {
                        broadcast_update_to 'users', partial: 'users/users_count', locals: { users: User.all },
                                                       target: 'users'
                      }
  def decorated
    UserDecorator.new self
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # def after_sign_in_path_for(_resource)
  #   homes_path
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name surname contact_number email password])
    # devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :surname, :contact_number, :email, :password, :current_password) }
  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore

    err_message = t "#{policy_name}.#{exception.query}", scope: 'pundit', default: :default
    render json: { message: err_message }, status: :unauthorized
  end
end

app/controllers/drag_controller.rb
class DragController < ApplicationController
  def item
    @genere = Genere.find(drag_item_params[:id])
    @genere.insert_at(drag_item_params[:position].to_i + 1)
  end

  private

  def drag_item_params
    params.require(:resource).permit(:id, :position)
  end
end

app/controllers/generes_controller.rb
class GeneresController < ApplicationController
  include Pundit::Authorization
  before_action :set_genere, only: %i[show edit update destroy]

  # GET /generes or /generes.json
  def index
    @generes = Genere.all.order(position: :asc)
  end

  # GET /generes/1 or /generes/1.json
  def show
    @uploads = @genere.uploads
  end

  # GET /generes/new
  def new
    @genere = Genere.new
    authorize @genere
  end

  # GET /generes/1/edit
  def edit
    authorize @genere
  end

  # POST /generes or /generes.json
  def create
    @genere = Genere.new(genere_params)
    authorize @genere
    respond_to do |format|
      if @genere.save
        format.html { redirect_to generes_path, notice: 'Genere was successfully created.' }
        format.json { render :show, status: :created, location: @genere }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @genere.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /generes/1 or /generes/1.json
  def update
    authorize @genere
    respond_to do |format|
      if @genere.update(genere_params)
        format.html { redirect_to genere_url(@genere), notice: 'Genere was successfully updated.' }
        format.json { render :show, status: :ok, location: @genere }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @genere.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /generes/1 or /generes/1.json
  def destroy
    @genere.destroy

    respond_to do |format|
      format.html { redirect_to generes_url, notice: 'Genere was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_genere
    @genere = Genere.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def genere_params
    params.require(:genere).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = HomeDecorator.decorate_collection(User.all)
  end

  # @route GET /turbo_frame_form
  def turbo_frame_form; end

  # @route POST /turbo_frame_submit
  def turbo_frame_submit
    extracted_anynumber = params[:any][:anynumber]
    render :turbo_frame_form, status: :ok, locals: { anynumber: extracted_anynumber, comment: 'turbo_frame_submit ok' }
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  include Pundit::Authorization
  before_action :set_upload, only: %i[show edit update destroy]

  # GET /uploads or /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1 or /uploads/1.json
  def show; end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit; end

  # POST /uploads or /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to upload_url(@upload), notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1 or /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to upload_url(@upload), notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1 or /uploads/1.json
  def destroy
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url, notice: 'Upload was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_upload
    @upload = Upload.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def upload_params
    params.require(:upload).permit(:generes_id, :users_id, :name, :link)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pundit::Authorization
  def index
    @users = User.order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drag_helper.rb
module DragHelper
end

app/helpers/generes_helper.rb
module GeneresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/turbo_devise_helper.rb
module TurboDeviseHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/generes/_form.html.erb
<%= form_with(model: genere) do |form| %>
  <% if genere.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(genere.errors.count, "error") %> prohibited this genere from being saved:</h2>

      <ul>
        <% genere.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/generes/edit.html.erb
<h1>Editing genere</h1>

<%= render "form", genere: @genere %>

<br>

<div>
  <%= link_to "Show this genere", @genere %> |
  <%= link_to "Back to generes", generes_path %>
</div>

app/views/generes/index.html.erb
<p style="color: green"><%= notice %></p>

<% if current_user.admin? %>
  <%= link_to "New genere", new_genere_path, class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back', home_dashboard_path, class: 'btn btn-danger' %>
<h1>Generes</h1>
<% dragActions = "dragstart->drag#dragStart
                  dragover->drag#dragOver
                  dragenter->drag#dragEnter
                  drop->drag#drop
                  dragend->drag#dragEnd" %>
<div id="generes">
  <% @generes.in_groups_of(10, false).each do |group| %>
    <div class='row'>
      <% group.each do |genere| %>
        <%= content_tag(:div, class: 'col-md-2 draggable', draggable: true, data: {
                                controller: 'drag',
                                action: dragActions,
                                resource_id: genere.id,
                                url: "/drag/item",
                                parent: 'generes'
                              }) do %>
              <%= link_to genere.name, genere, class: 'btn btn-warning'%>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/generes/new.html.erb
<h1>New genere</h1>

<%= render "form", genere: @genere %>

<br>

<div>
  <%= link_to "Back to generes", generes_path %>
</div>

app/views/generes/show.html.erb
<p style="color: green"><%= notice %></p>
<%= button_to "Destroy this genere", @genere, method: :delete, class: "btn btn-danger" %>

<div id="uploads">
  <%# @uploads.in_groups_of(10, false).each do |group| %>
    <div class='row'>
      <%# group.each do |upload| %>
        <div class='col-md-2'>
          <%# <%= link_to genere.name, genere, class: 'btn btn-warning' %>
          <%= image_tag("https://pixabay.com/photos/tree-sunset-clouds-sky-silhouette-736885/") %>
        </div>
      <%# end %>
    </div>
  <%# end %>
</div>

<div>
  <%= link_to "Edit this genere", edit_genere_path(@genere) %> |
  <%= link_to "Back to generes", generes_path %>
</div>

app/views/home/index.html.erb
<div class='container-sm'>
  <figure class="text-end">
    <blockquote class="blockquote">
      <p>A well-known quote, contained in a blockquote element.</p>
    </blockquote>
    <figcaption class="blockquote-footer">
      Someone famous in <cite title="Source Title">Source Title</cite>
    </figcaption>
  </figure>
</div>
<button class="link">Clicky</button>
<% if current_user.admin? %>
  <%= turbo_stream_from(:users) %>
  <div id="users">
    <%= render partial: 'users/users_count', locals: { users: @users } %>
  </div>
  <%= link_to 'Users', users_list_path, class: 'btn btn-primary'%>
<% end %>
<%= link_to 'Genere', generes_path, class: 'btn btn-primary'%>

<h1>This is home</h1>
<%= turbo_frame_tag 'anyframe' do %>        
  <div>
    <h2>Home view</h2>
    <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
      <%= form.label :anynumber, 'Type an integer (odd or even)', class: 'my-0  d-inline'  %>
      <%= form.text_field :anynumber, type: 'number',required: true, value: "#{local_assigns[:anynumber] || 0}", 'aria-describedby' => 'anynumber' %>
      <%= form.submit 'Submit this number', id: 'submit-number' %>
    <% end %>
  <div>
<% end %>

app/views/home/turbo_frame_form.html.erb
<section>
  <%= turbo_frame_tag 'anyframe' do %>    
    <div>
      <h2>Frame view</h2>
      <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
          <%= form.label :anynumber, 'Type an integer (odd or even)', class: 'my-0  d-inline'  %>
          <%= form.text_field :anynumber, type: 'number', required: true, value: "#{local_assigns[:anynumber] || 0}", 'aria-describedby' => 'anynumber' %>
          <%= form.submit 'Submit this number', id: 'submit-number' %>
      <% end %>
    </div>
    <div>
      <h2>Data of the view</h2>
      <pre style="font-size: .7rem;"><%= JSON.pretty_generate(local_assigns) %></pre> 
    </div>
    
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusHotwireDemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        
        <%= link_to "Log Out", destroy_user_session_path, 'data-turbo-method': :delete, 'data-turbo-confirm': "Do you want to Logout?", class: 'btn btn-warning'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
        <%= link_to "Sign in", new_user_session_path, class: 'navbar-link', data: { 'turbo-action': "replace" }  %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/uploads/_form.html.erb
<%= form_with(model: upload) do |form| %>
  <% if upload.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
        <% upload.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :generes_id, style: "display: block" %>
    <%= form.text_field :generes_id %>
  </div>

  <div>
    <%= form.label :users_id, style: "display: block" %>
    <%= form.text_field :users_id %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :link, style: "display: block" %>
    <%= form.text_field :link %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/uploads/_upload.html.erb
<div id="<%= dom_id upload %>">
  <p>
    <strong>Generes:</strong>
    <%= upload.generes_id %>
  </p>

  <p>
    <strong>Users:</strong>
    <%= upload.users_id %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= upload.name %>
  </p>

  <p>
    <strong>Link:</strong>
    <%= upload.link %>
  </p>

</div>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render "form", upload: @upload %>

<br>

<div>
  <%= link_to "Show this upload", @upload %> |
  <%= link_to "Back to uploads", uploads_path %>
</div>

app/views/uploads/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Uploads</h1>

<div id="uploads">
  <% @uploads.each do |upload| %>
    <%= render upload %>
    <p>
      <%= link_to "Show this upload", upload %>
    </p>
  <% end %>
</div>

<%= link_to "New upload", new_upload_path %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render "form", upload: @upload %>

<br>

<div>
  <%= link_to "Back to uploads", uploads_path %>
</div>

app/views/uploads/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @upload %>

<div>
  <%= link_to "Edit this upload", edit_upload_path(@upload) %> |
  <%= link_to "Back to uploads", uploads_path %>

  <%= button_to "Destroy this upload", @upload, method: :delete %>
</div>

app/views/users/_users_count.html.erb
<div class="users">
  <%= users.size %>
</div>

app/views/users/index.html.erb
<% if @users.empty? %>
  <h4>There are no teams in the system at this time.</h4>
<% else %>
  <h1>Users</h1>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Admin</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.surname %></td>
          <td><%= user.role %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to "Back to Home", home_dashboard_path %>
<% end %>